
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openframe-config
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: openframe-config
  template:
    metadata:
      labels:
        app: openframe-config
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        prometheus.io/port: "8889"
        prometheus.io/path: "/management/{{ default .Values.global.image.tag .Values.image.tag }}/prometheus"
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.43.0.10
        searches:
          - svc.cluster.local
          - cluster.local
        options:
          - {name: ndots, value: "2"}
          - {name: timeout, value: "2"}
          - {name: attempts, value: "3"}
      hostAliases:
        - {ip: "20.26.156.215", hostnames: ["github.com"]}
        - {ip: "20.26.156.216", hostnames: ["codeload.github.com"]}
        - {ip: "20.26.156.210", hostnames: ["api.github.com"]}

      containers:
        - name: openframe-config
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ default .Values.global.image.tag .Values.image.tag }}"
          ports:
            - containerPort: 8888
              name: http
            - containerPort: 8889
              name: management

          envFrom:
            - configMapRef:
                name: microservices
            - configMapRef:
                name: openframe-config
          env:
            - name: RELEASE_VERSION
              value: "{{ default .Values.global.image.tag .Values.image.tag }}"
            - name: JAVA_TOOL_OPTIONS
              value: "-Djava.net.preferIPv4Stack=true"

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          startupProbe:
            httpGet:
              path: /xml/shared-logback-spring.xml
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /xml/shared-logback-spring.xml
              port: http
            initialDelaySeconds: 300
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /xml/shared-logback-spring.xml
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
