apiVersion: apps/v1
kind: Deployment
metadata:
  name: tactical-frontend
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/match-tag: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: tactical-frontend
  template:
    metadata:
      labels:
        app: tactical-frontend
      {{- with .Values.tactical.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.43.0.10
        searches:
          - svc.cluster.local
          - cluster.local
        options:
          - {name: ndots, value: "2"}
          - {name: timeout, value: "2"}
          - {name: attempts, value: "3"}
      hostAliases:
        - {ip: "20.26.156.215", hostnames: ["github.com"]}
        - {ip: "20.26.156.216", hostnames: ["codeload.github.com"]}
        - {ip: "20.26.156.210", hostnames: ["api.github.com"]}
      securityContext:
        runAsNonRoot: true

      containers:
      - name: tactical-frontend
        image: "{{ .Values.tactical.frontend.image.registry }}/{{ .Values.tactical.frontend.image.repository }}:{{ .Values.tactical.frontend.image.tag }}"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: tactical-frontend

        resources:
            {{- toYaml .Values.tactical.frontend.resources | nindent 12 }}

        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
