apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tactical-nginx
spec:
  serviceName: tactical-nginx
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tactical-nginx
  template:
    metadata:
      labels:
        app: tactical-nginx
      {{- with .Values.tactical.nginx.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.43.0.10
        searches:
          - svc.cluster.local
          - cluster.local
        options:
          - {name: ndots, value: "2"}
          - {name: timeout, value: "2"}
          - {name: attempts, value: "3"}
      hostAliases:
        - {ip: "20.26.156.215", hostnames: ["github.com"]}
        - {ip: "20.26.156.216", hostnames: ["codeload.github.com"]}
        - {ip: "20.26.156.210", hostnames: ["api.github.com"]}
      priorityClassName: tactical-rmm

      containers:
      - name: tactical-nginx
        image: "{{ .Values.tactical.nginx.image.registry }}/{{ .Values.tactical.nginx.image.repository }}:{{ .Values.tactical.nginx.image.tag }}"
        ports:
        - containerPort: 8080
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: tactical-nginx
        startupProbe:
          httpGet:
            path: /nginx_status
            port: 8081
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /nginx_status
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10

        volumeMounts:
        - name: nginx-data
          mountPath: /opt/tactical
      volumes:
      - name: nginx-data
        persistentVolumeClaim:
          claimName: tactical-nginx
