apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-server
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: authentik-server
  template:
    metadata:
      labels:
        app: authentik-server
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.43.0.10
        searches:
          - svc.cluster.local
          - cluster.local
        options:
          - {name: ndots, value: "2"}
          - {name: timeout, value: "2"}
          - {name: attempts, value: "3"}
      hostAliases:
        - {ip: "20.26.156.215", hostnames: ["github.com"]}
        - {ip: "20.26.156.216", hostnames: ["codeload.github.com"]}
        - {ip: "20.26.156.210", hostnames: ["api.github.com"]}

      initContainers:
      - name: wait-for-postgres
        image: postgres:latest
        command: ['sh', '-c',
          'until pg_isready -h "$POSTGRES_HOST" -U "$POSTGRES_USER" -d "$POSTGRES_DB"; do echo waiting for postgres; sleep 2; done;']
        envFrom:
        - configMapRef:
            name: authentik-postgres
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-postgres
              key: POSTGRES_PASSWORD

      - name: wait-for-redis
        image: redis:latest
        command: ['sh', '-c',
          'until redis-cli -h redis-authentik-headless.integrated-tools.svc.cluster.local ping | grep -q PONG; do echo waiting for redis; sleep 2; done;']

      containers:
      - name: server
        image: ghcr.io/goauthentik/server:latest
        args: ["server"]
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: authentik-server
        - secretRef:
            name: authentik-server
        - secretRef:
            name: authentik-postgres
        resources:
          limits:
            cpu: 150m
            memory: 1024Mi
        startupProbe:
          httpGet:
            path: /-/health/live/
            port: http
          failureThreshold: 2000
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /-/health/live/
            port: http
          failureThreshold: 2000
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /-/health/ready/
            port: http
            scheme: HTTP
          failureThreshold: 2000
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - name: media
          mountPath: /media
        - name: certs
          mountPath: /certs
        - name: templates
          mountPath: /templates
      volumes:
      - name: media
        emptyDir: {}
      - name: certs
        emptyDir: {}
      - name: templates
        emptyDir: {}
          
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: authentik-worker
  template:
    metadata:
      labels:
        app: authentik-worker
      {{- with .Values.worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    
      initContainers:
      - name: wait-for-postgres
        image: postgres:latest
        command: ['sh', '-c',
          'until pg_isready -h "$POSTGRES_HOST" -U "$POSTGRES_USER" -d "$POSTGRES_DB"; do echo waiting for postgres; sleep 2; done;']
        envFrom:
        - configMapRef:
            name: authentik-postgres
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-postgres
              key: POSTGRES_PASSWORD

      - name: wait-for-redis
        image: redis:latest
        command: ['sh', '-c',
          'until redis-cli -h redis-authentik-headless.integrated-tools.svc.cluster.local ping | grep -q PONG; do echo waiting for redis; sleep 2; done;']

      - name: wait-for-server
        image: {{ .Values.registerJob.image.registry }}/{{ .Values.registerJob.image.repository }}:{{ .Values.registerJob.image.tag }}
        command: ['sh', '-c',
          'until curl -s http://authentik-server:9000/-/health/ready/; do echo waiting for authentik-server; sleep 2; done;']

      containers:
      - name: worker
        image: ghcr.io/goauthentik/server:latest
        args: ["worker"]
        envFrom:
        - configMapRef:
            name: authentik-server
        - secretRef:
            name: authentik-server
        - secretRef:
            name: authentik-postgres
        resources:
          limits:
            cpu: 150m
            memory: 1024Mi
        startupProbe:
          exec:
            command:
              - ak
              - healthcheck
          failureThreshold: 2000
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        livenessProbe:
          exec:
            command:
              - ak
              - healthcheck
          failureThreshold: 2000
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
              - ak
              - healthcheck
          failureThreshold: 2000
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        volumeMounts:
        - name: media
          mountPath: /media
        - name: certs
          mountPath: /certs
        - name: templates
          mountPath: /templates
      volumes:
      - name: media
        emptyDir: {}
      - name: certs
        emptyDir: {}
      - name: templates
        emptyDir: {}
