apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tactical-postgres
spec:
  serviceName: tactical-postgres
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tactical-postgres
  template:
    metadata:
      labels:
        app: tactical-postgres
      {{- with .Values.postgres.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.43.0.10
        searches:
          - svc.cluster.local
          - cluster.local
        options:
          - {name: ndots, value: "2"}
          - {name: timeout, value: "2"}
          - {name: attempts, value: "3"}
      hostAliases:
        - {ip: "20.26.156.215", hostnames: ["github.com"]}
        - {ip: "20.26.156.216", hostnames: ["codeload.github.com"]}
        - {ip: "20.26.156.210", hostnames: ["api.github.com"]}
      priorityClassName: postgres-tactical

      containers:
      - name: postgres
        image: {{ .Values.postgres.image.registry }}/{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
        args:
          - "-c"
          - "wal_level=logical"
          - "-c"
          - "max_wal_size=512MB"
        ports:
        - containerPort: 5432
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        envFrom:
        - configMapRef:
            name: tactical-postgres
        - secretRef:
            name: tactical-postgres
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 30
          periodSeconds: 10

        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data

      {{- if .Values.postgres.metrics.enabled }}
      - name: postgres-exporter
        image: {{ .Values.postgres.metrics.image.registry }}/{{ .Values.postgres.metrics.image.repository }}:{{ .Values.postgres.metrics.image.tag }}
        ports:
        - name: metrics
          containerPort: 9187
        env:
        - name: DATA_SOURCE_USER
          valueFrom:
            secretKeyRef:
              name: tactical-postgres
              key: POSTGRES_USER
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              name: tactical-postgres
              key: POSTGRES_PASSWORD
        - name: DATA_SOURCE_URI
          value: "localhost:5432?sslmode=disable"
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.postgres.metrics.resources | nindent 10 }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
      {{- end }}

  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
